/*
1094 - EXPERIÊNCIAS

MARIA ACABOU DE INICIAR SEU CURSO DE GRADUAÇÃO NA FACULDADE DE MEDICINA E PRECISA DE
SUA AJUDA PARA ORGANIZAR OS EXPERIMENTOS DE UM LABORATÓRIO O QUAL ELA É RESPONSÁVEL.
ELA QUER SABER NO FINAL DO ANO, QUANTAS COBAIAS FORAM UTILIZADAS NO LABORATÓRIO E O 
PORCENTUAL DE CADA TIPO DE COBAIA UTILIZADA.

ESTE LABORATÓRIO EM ESPECIAL UTILIZA TRÊS TIPOS DE COBAIAS: SAPOS, RATOS E COELHOS. PARA
OBTER ESTAS INFORMAÇÕES, ELA SABE EXATAMENTE O NÚMERO DE EXPERIMENTOS QUE FORAM
REALIZADOS, O TIPO DE COBAIA UTILIZADA E A QUANTIDADE DE COBAIAS UTILIZADAS EM CADA
EXPERIMENTO.

ENTRADA:A PRIMEIRA LINHA DE ENTRADA CONTÉM UM VALOR INTEIRO N QUE INDICA OS VÁRIOS CASOS DE
TESTE QUE VEM A SEGUIR. CADA CASO DE TESTE CONTÉM UM INTEIRO QUANTIA (1 <= QUANTIA <= 
15) QUE REPRESENTA A QUANTIDADE DE COBAIAS UTILIZADAS E UM CARACTERE TIPO ('C', 'R' OU 
'S'), INDICANDO O TIPO DE COBAIA (R: RATOS S: SAPO C: COELHO).

SAÍDA: APRESENTE O TOTAL DE COBAIAS UTILIZADAS, O TOTAL DE CADA TIPO DE COBAIA UTILIZADA E O
PERCENTUAL DE CADA UMA EM RELAÇÃO AO TOTAL DE COBAIAS UTILIZADAS, SENDO QUE O
PERCENTUAL DEVE SER APRESENTADO COM DOÍS DÍGITOS APÓS O PONTO.
*/

//biblioteca
#include <iostream>

using namespace std;

//função principal
int main()
{
    //declaração de dados

    //entrada de dados

    //desenvolvimento

    //saída de dados

    return 0;
}
